before_script:
  - npm install
cache:
  paths:
    - node_modules/
pages:
  stage: deploy
  script:
    - npm run cp
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
